### ISSUE TITLE
The website linked from README is gone

### ISSUE THREAD

**Issue by mvasilkov** [skosch/Crimson#14]

**Comment by skosch** [comment]
Thanks, fixed!

**Comment by adrientetar** [comment]
@skosch By the way I get "invalid certificate" when trying to access your website over https. And via http it just returns a welcome message from the server, I think you should set up a redirection.

**Comment by adrientetar** [comment]
@skosch, Ouch, I just pushed wip refactoring commits to the master branch by accident. Could use a force-push if that's a problem. Very sorry about that.
