### ISSUE TITLE
Ligatures for italic

### ISSUE THREAD

**Issue by katef** [skosch/Crimson#18]
The italic face puts "fi" awfully close together, and these would suit a ligature to give a less cluttered feel. I didn't check, but I suspect the same would be true for the other usual ligatures, fl, ffi and such.

Thank you,

**Comment by katef** [comment]
@skosch pointed out that there exists a `f_i` ligature at U+FB01. It looks like the current substitutions for the `liga` feature map `fi` to substitute literally `f i`. I suppose those are there as a handy placeholder. So my request is to have those substitute f_i instead.

I'd offer a patch, but for some reason my fontforge is showing most (but not all!) glyphs as blank, and that's true when I generate an otf font, too. So I can't test that. But here's all I did:
````diff
-Ligature2: "'liga' Ligatures standard lookups5-1" f i
+Ligature2: "'liga' Ligatures standard lookups5-1" f_i
````

**Comment by NumericalEvolution** [comment]
This also happens for italic "ch" [pic](http://i.imgur.com/ZWX8dH9.png).

**Comment by skosch** [comment]
@NumericalEvolution are you using an old (i.e. Google's) version?
@katef Thanks for trying :) I'll look into it later today!

**Comment by NumericalEvolution** [comment]
@skosch I use the one provided by Adobe Edge Fonts. As I understand, it's fixed now?

**Comment by katef** [comment]
@NumericalEvolution Yes - the `ch` spacing looks fixed to me, for the current version from git.

**Comment by katef** [comment]
Oh, had someone already committed this? I must've been confused! The current revision seems to have `fi` and similar present for the `liga` feature for the Italic face.

I'm going to mark it closed. False alarm :)
