### ISSUE TITLE
Add PANOSE values for all faces

### ISSUE THREAD

**Issue by katef** [skosch/Crimson#22]
Currently just Roman has [PANOSE values](https://en.wikipedia.org/wiki/PANOSE) set:
````
Panose: 2 0 5 3 0 0 0 0 0 0
````

**Comment by skosch** [comment]
... wow, you're really cleaning up in here! :) :+1:

**Comment by katef** [comment]
But first proposed corrected values for Roman, since the existing ones seem to be gibberish:
````diff
-Panose: 2 0 5 3 0 0 0 0 0 0
+Panose: 2 3 5 3 6 4 6 2 3 4
````

**Comment by katef** [comment]
Committed in katef/Crimson@7a851de527ae8aa753469562a48cfdf08a5557d5. If you think that looks alright, I'll make a pull request (or whatever. I'm not super familiar with github).

**Comment by katef** [comment]
Committed in 0d1c492. It would be nice if somebody could check I got them right.
