### ISSUE TITLE
Web fonts are gone and new TTF files have old vertical metrics

### ISSUE THREAD

**Issue by rainerschuhsler** [skosch/Crimson#3]
I commented on the last issue but I'm opening a new one just in case my comment wasn't seen. 

The last commit was more destructive than constructive.

The web fonts should not have been removed. The TTF web fonts aren't meant to be installed as desktop fonts; they were generated to have a basic subsetting for browsers to download them faster and to have an adjusted x-height to match Georgia. Font Squirrel did not touch the settings for hinting, so the differences in hinting between the web TTF files and the new desktop TTF files weren't caused by the generator.

It looks like ttfautohint improved the hinting of the TTF files on Windows, but I fail to see why this is necessary at all, when the OTF files are technically superior. The reason the TTF files appear to render "better" on Windows (at least at small point sizes) is the way they're aliased. As you can see by the 72pt size type, the OTF characters appear smooth while the TTF characters appear jagged. I'll concede that Windows desktop users should have to option to install TTF files if they prefer them over OTF fonts, but these files shouldn't outright replace the web versions.

Further, it appears the new TTF files were generated by the SRF files, which retain the issues with vertical metrics that are fixed in the OTF files, so new web fonts can't be generated from the new TTF files because the baseline will be inconsistent among different weights. See http://uh.edu/~jrschuhs/crimson/December-2013/baseline-test.html and http://uh.edu/~jrschuhs/crimson/May-2014/baseline-test.html to compare.

**Comment by orjanb-ne** [comment]
This seems like it is still an issue. I downloaded the latest webfont and get this:
[
![crimson-alignment](https://user-images.githubusercontent.com/22000464/48253301-3f239280-e407-11e8-8bcb-86156abce063.png)
](url)
![helvetica-alignment](https://user-images.githubusercontent.com/22000464/48253313-464aa080-e407-11e8-954c-970c6f9229a0.png)
