### ISSUE TITLE
Italic long S shouldn't have an arm

### ISSUE THREAD

**Issue by katef** [skosch/Crimson#40]
I've been looking at similar typefaces; for those which have an arm for an f-like ſ, their corresponding italic faces do not have an arm. I think Crimson's italic should follow suite.

**Comment by skosch** [comment]
Totally should not have an arm. Amputate before it grows another one!

**Comment by katef** [comment]
Is that the case for italic ß too?

**Comment by skosch** [comment]
I'd say so, yeah.

**Comment by katef** [comment]
Committed in c9d7640.
