### ISSUE TITLE
Do something with long s for smcp

### ISSUE THREAD

**Issue by katef** [skosch/Crimson#41]
Curiously I see Minion Pro leaves ſ as-is under `smcp`. But other typefaces substitute it for a smallcap `S`. There's also an obscure capital ſ form, which looks like a ʕ. I've never seen that used, and I doubt anybody would recognise it, but it does exist.

My complaint about leaving ſ is that I'd expect a consistent x-height from `smcp`, and this glyph breaks that. So I think we should do ''something'' with it. My hunch would be to substitute ſ for `s.sc`, but I don't know if that would annoy people.

**Comment by skosch** [comment]
+1 for ſ → s.sc
