### ISSUE TITLE
Font size is rendered too small on iPhone 6 (latest OS)

### ISSUE THREAD

**Issue by perandre** [skosch/Crimson#51]
![comp](https://cloud.githubusercontent.com/assets/118979/15965818/6a7247b8-2f20-11e6-9487-8d5aafafcc1c.png)

Using the version on Google Fonts, the font rendering is buggy on my iPhone 6. This is true for both semibold and roman, at least.

**Comment by perandre** [comment]
Rendering in Sketch corresponds to what I see in Chrome on Mac, however.

**Comment by skosch** [comment]
@perandre I wish I could help, but the issue is that Google is serving you an ancient version of the font, and so far they've ignored all requests to upgrade (@davelab6 hint hint :smirk:)

**Comment by perandre** [comment]
@skosch Ah, thanks! I'll switch to self hosted and test (and update issue title!). Closing!
