### ISSUE TITLE
old style numerals

### ISSUE THREAD

**Issue by pdattx** [skosch/Crimson#52]
Maybe it's possible to set the old style numerals figures very easy, 'cause the numbers seems to fit very good if there are in other positions for the oldstyle.

Just a thought...

**Comment by skosch** [comment]
Not sure I understand your question, can you clarify? You can use whichever figures you like best.

**Comment by pdattx** [comment]
I mean something like this:
http://f.tqn.com/y/desktoppub/1/S/I/r/3/4FigureStyles.PNG

The oldstyle mubers are sometimes a variation, because of the weight. Like the bottom circle from the eight, but I don't know if it's necessary - just the other positioning of numbers would be awesome.

**Comment by skosch** [comment]
Oldstyle numerals are already available in the font, starting at glyph 1206 – check the `onum` OpenType feature. How to access them depends on your OS and application, though.

**Comment by pdattx** [comment]
Well, the css-command for that seems to be:
-moz-font-feature-settings:"onum" 1;
-ms-font-feature-settings:"onum" 1;
-o-font-feature-settings:"onum" 1;
-webkit-font-feature-settings:"onum" 1;
font-feature-settings:"onum" 1; 

but the webfont doesn't react with that. What is my mistake?

**Comment by skosch** [comment]
If I remember correctly, the webfonts in this repo have many of those "special" glyphs removed, because they're rarely used. You can use tools like the webfont generator at fontsquirrel.com to subset your own webfonts from the desktop versions, though.

**Comment by pdattx** [comment]
ok, thx
