### ISSUE TITLE
some kerning pairs involving "a" are off point.

### ISSUE THREAD

**Issue by demoy** [skosch/Crimson#59]
![screenshot_20170319_123543](https://cloud.githubusercontent.com/assets/2396524/24108009/53f49fcc-0d5a-11e7-87fb-b19f4c22e411.png)

a+b, a+f, a+i, a+m, a+n, a+r, a+t, a+u, and a+z. Have too much spacing relative to the other a combinations making words containing those combinations appear to have gaps. 

Note: using (linux) opensuse tumbleweed.

**Comment by skosch** [comment]
What the heck, I've never seen this before. The kerning looks wonky all over, even between letters (e.g. `au`). What font file is this? Are you on the `ufo` branch?

**Comment by demoy** [comment]
@skosch, I been using the precompile otf file since saturday.

**Comment by demoy** [comment]
Here is a small section taken from calibre ![screenshot_20170320_114711](https://cloud.githubusercontent.com/assets/2396524/24110981/fe234cde-0d62-11e7-912a-d2559b891911.png). Pay attension only to "a"s:  notice that the space [ IE " "] following  the word "a" is wider than the space preceding it.

**Comment by skosch** [comment]
Can you do me a favour and try the file from the "ufo" branch? It's the up-and-coming (and hopefully cleaned-up) version. Could you report back whether the issue is fixed there? Thank you!

**Comment by demoy** [comment]
@skosch okay

**Comment by demoy** [comment]
@skosch thanks, that solved it.

**Comment by skosch** [comment]
Cool. There's a good chance that other things are off with those files, though, especially regarding vertical metrics. Please report back if you notice anything amiss!
