### ISSUE TITLE
Double-quotes and literary double-quotes rendered as simple quote

### ISSUE THREAD

**Issue by mratsim** [skosch/Crimson#65]
I'm testing the font from Google https://fonts.google.com/specimen/Crimson+Text and found 2 issues:

Here are the styles

![2018-01-20_15-15-04](https://user-images.githubusercontent.com/22738317/35184366-e4dfd322-fdf4-11e7-81f7-6bba944773fc.png)

1. Semi-bold italic of double-quote " " is a simple quote
![image](https://user-images.githubusercontent.com/22738317/35184374-f7da200e-fdf4-11e7-898e-c3e9471a1c4f.png)

2. The closing literary bold double-quote “ ” is a simple quote
![image](https://user-images.githubusercontent.com/22738317/35184615-5abd20d8-fdf8-11e7-9e23-dbf32e9a3b05.png)

**Comment by skosch** [comment]
Thanks @mratsim for the bug report!
The version of the font you are looking at is actually years behind the current state of this repository. If you have issues with Google's version, I suggest you open an issue in the [Google Fonts repo](https://github.com/google/fonts).
