### ISSUE TITLE
Crimson Roman 'a' kerning broken

### ISSUE THREAD

**Issue by arthurattwell** [skosch/Crimson#66]
Commit 553aa7b caused a problem with kerning after the letter `a`.

Before that commit, at 5b3f19c, kerning was great:

![crimson-roman-at-5b3f19c](https://user-images.githubusercontent.com/1053331/36021436-7000314c-0d8e-11e8-92d7-2af1b35b7c3a.png)

But at 553aa7b, this happened:

![crimson-roman-at-553aa7b](https://user-images.githubusercontent.com/1053331/36021462-80bc2856-0d8e-11e8-8daa-43df1b0f5da5.png)

I don't know enough about the source files to find the exact change that caused the problem.

**Comment by skosch** [comment]
Oh. That is interesting. Thank you!

**Comment by jco2** [comment]
The issue is still present. I corrected the kerning manually, would you accept a PR ?
