### ISSUE TITLE
Kerning issues with accented characters in italics font

### ISSUE THREAD

**Issue by cpitclaudel** [skosch/Crimson#77]
Hi there,

How up-to-date is the version of the font on Google Fonts? While trying out the accent support, I noticed some kerning issues around accented characters, in particular é:

![crimson](https://user-images.githubusercontent.com/8181630/83369130-cef2ae00-a3aa-11ea-8b23-525ccb341258.png)

There are big gaps in caf-é and in T-étar.  Is this a bug?

Thanks a lot for your work!

**Comment by skosch** [comment]
Not up to date at all! Try [Amiri](https://fonts.google.com/specimen/Amiri) or [Crimson Pro](https://fonts.google.com/specimen/Crimson+Pro?vfonly) instead :)

**Comment by cpitclaudel** [comment]
Thanks a lot!  And thanks for your work :)
