### ISSUE TITLE
.woff2 Font Request Status

### ISSUE THREAD

**Issue by HelpMeOuch** [skosch/Crimson#83]
Greetings Sebastian!

I am working on a website and want to use Crimson as the font set. Squarespace requires .ttf/.otf, .woff, and .woff2 formats of the font to function on the platform. I was able to find all but the .woff2. Do you have plans to format Crimson into .woff2, or has that already been done and I've missed it?

Thank you for your time, and I hope you have a fantastic day!

Stephanie

**Comment by skosch** [comment]
Hi Stephanie, have you considered using a CDN like Google Fonts? You can get either Crimson Pro directly, or you can use [Amiri](https://fonts.google.com/specimen/Amiri), which uses the 2012 version of Crimson for its Latin character set. If you need more fine-grained control, take a look at the webfont generator at fontsquirrel.com :slightly_smiling_face:

**Comment by HelpMeOuch** [comment]
> Hi Stephanie, have you considered using a CDN like Google Fonts? You can get either Crimson Pro directly, or you can use [Amiri](https://fonts.google.com/specimen/Amiri), which uses the 2012 version of Crimson for its Latin character set. If you need more fine-grained control, take a look at the webfont generator at fontsquirrel.com 🙂

I was unaware that those were available to me! Huzzah 🤓 I shall check into the options you've suggested. Thank you so much for your quick and helpful reply! Have an excellent rest of your day 😁
